import type { Metadata } from "next";
import "./globals.css";
import { SuitContext } from "@/lib/components/SuitContext";
import Nav from "@/lib/components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav></Nav>
        <SuitContext>{children}</SuitContext>
      </body>
    </html>
  );
}
